services:
    web:
        build: .
        container_name: odoo
        depends_on:
            - db
        ports:
            - "8069:8069"
            - "5678:5678"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./odoo.conf:/etc/odoo/odoo.conf
        environment:
            - PYDEVD_DISABLE_FILE_VALIDATION=1
        command:
            [
                "python3",
                "-Xfrozen_modules=off",
                "-m",
                "debugpy",
                "--listen",
                "0.0.0.0:5678",
                "--wait-for-client",
                "-m",
                "odoo",
                "--config=/etc/odoo/odoo.conf",
                "--dev=all",
                "--init=base",
            ]
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
